
jwt:
  access_token_secret: FNW1h2tNWMIYg0XQMvaSh8T4F47dH58RB31rQG4sfzI=--Has59bEusfvzblM3o/gPuA==
  refresh_token_secret: cnA+6U7IrHUSSd3cv0DHjrifQCCYRc6GgytNEpTzuDg=--DzMqgh6PfFn+cHXjyrva9A==

swagger:
  username: uNBrmxucXyni+13ClLyR+xKGuFbtAhCisV4IL+XOVys=--W8jtM2zYbhXCBm7D0iY+Ew==
  password: P+eX64FL5Pl2flmCvc1wEuX8iH+LUh67uu8Q0x86fD4=--bXMFxDlxadas2f88tnpPVw==

database:
  name: MovRlCmFVMDQq5X2Fho8iK2uTgHjznQQfYu8oslg4js=--LTARaP9QrtJ/wc5phF6Htw==
  host: jFeFjGMPJtIDBXw8O0FE2w==--Ywl2aGn3jqo3iRDRF+zSFA==
  username: d6veWY4aj83vV8lHIg9J5w==--mPEDr9Qb3uky0ff+ZxIP6A==
  password: erMlOes1dUiqVIN72W0seQ==--uhi5W+SGD+WgjAw4C5p5MQ==
  port: /PQIlaqlTSXRt/CrdsOrTQ==--KHOTFHlQO7EHu8L4K2FXkw==

emailLogin:
  tables: ABHKzfRGZd94T/OxH0ilNQ==--zBzpukcQZffRtvppXcmijw==
  passwordMinLength: M0+xCHmWvgcWmT+OZ+l74g==--MzAQsib9x5fJ3rHY6Bu1JQ==
  rememberFor: qTPJZYTq2CzeHiTLEGbD4w==--24w/7JfpYzks1Kr7E3nFXQ==
  resetPasswordWithin: Rjk1uAYGC07IxjaZWdKVFQ==--sr+nWae24PQ/ehlJ4nChyg==
  maximumRetries: j37Izk/c1dtwcdFz8+5mrQ==--1B0tgoGzCLnnztzhlPXmzA==
  unlockIn: fzeQfLsHzYwLVHcbDjjcRg==--bsfqYw9m1gks0fzlScsReg==
  passwordRegex: wPmxr8OWtxtXrE6QED4diXnJJIolw3pZzWgafdYsFlOGfU8OXDCZOZhaSI5+FI6NW/eG4OCDmdT07hxQVgDrZmx+HloO5/fdDzDq1vu4yP4=--+wtk8013Sn7jYwAXdc+gyQ==
  confirmationEmail: /fV76g1YayiCixoDiT+J5w==--caXJT5y9kogsGH/FIuK2qA==


