
jwt:
  access_token_secret: 7rcODV5K6mfGYN/Be+U/HLM/O1Ss5UbNeSbEHsYpR88=--xIOTtfc4o7CPbCrkyylYGg==
  refresh_token_secret: 6XL0zZ1zYwBVGgxRGtcjVEchahhnPNC8hqTWun3Wx60=--bnCJnWVwX2ldQ+Fbm297PQ==

swagger:
  username: zAFIOS/PIIdrCaaxGBcOZG/awzc51N5vFjTAGBn0U1c=--lKgDkuFPyyQAw/2uYGklkA==
  password: B+hT9HSVAJE+zmiTnAZlK4kV4a5LBrkgbq5FLszuWMU=--aC5WXQoKbOTJdK5e4k/y4g==

database:
  name: 7KdFpQZmTSAZstFBT3S8S7NSTgouaVuJoHozu8HnSVw=--Wl1C5Lsxio2ZSgM/i5z6cA==
  host: J5et2AXWWNo2ghbELnlQfQ==--xlgkIR3TjbE2Lr/Z5RXP5Q==
  username: DVl4mopr60RtooyZ3FZyxg==--TfRfE/BzXgRem85M3lAMwA==
  password: 8uac4gx38gcAYWlgc/vR5A==--mwNLtdHHH5wI5dZTV45QRA==
  port: L7n6q2gM8A2/uS6DajBtvw==--uoNZZhdDct8cVkRVxg/6EA==

emailLogin:
  tables: xMJuZL3l6Jt3XVe0omt9nw==--UoGhZyI1Z1seaJ39De/8vw==
  passwordMinLength: nyXknlwDQy6/bAEg4yEb1Q==--UR9zcA59Feu25J+7yo+JYw==
  rememberFor: DlxciWBQXTxvMd0s1v3bAg==--d5tKNAtJRKojWddYFT+F7Q==
  resetPasswordWithin: 81KQxSDaVCO0hvlaY/aGZg==--UBv4TPs9RlHruHgE5V3o2Q==
  maximumRetries: Ty2bj4/nm0Ycq8xRTTqGSA==--MMXDHahmgKsJl+kJwm/7NQ==
  unlockIn: N542aP2Yupq0hIZQqmw/+w==--5toOawthudUdh5PWyuDAFg==
  passwordRegex: FeIPVse6DNmwa9WxqBtSCdu9qyrLg+TbLosr6BV7TiCMMOwQG3qra3nQftJvQmzUZ74PxMvnCQVsXZZEIY+w37u+bXJMRvfceDR6z0wLURY=--gB6cJRdLgvQW/f3SpXjepQ==
  confirmationEmail: ohCMVVQCqqKGD2KTyNrEWQ==--4EyDHUuPhgwtPvQ0Zs6djw==


